image:
  repository: grafana/agent-operator
  pullPolicy: IfNotPresent
  tag: v0.44.3@sha256:6ab710d58bf081fe7228c1d933104d04b27a14a4f91fa83c44717aa68edbb68f

podOptions:
  automountServiceAccountToken: true

service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

workload:
  main:
    podSpec:
      containers:
        main:
          args:
            - "--kubelet-service={{ .Values.kubeletService.namespace }}/{{ .Values.kubeletService.serviceName }}"
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false

portal:
  open:
    enabled: false

rbac:
  main:
    enabled: true
    primary: true
    clusterWide: true
    rules:
      - apiGroups: [monitoring.grafana.com]
        resources:
          - grafanaagents
          - metricsinstances
          - logsinstances
          - podlogs
          - integrations
        verbs: [get, list, watch]
      - apiGroups: [monitoring.grafana.com]
        resources:
          - grafanaagents/finalizers
          - metricsinstances/finalizers
          - logsinstances/finalizers
          - podlogs/finalizers
          - integrations/finalizers
        verbs: [get, list, watch, update]
      - apiGroups: [monitoring.coreos.com]
        resources:
          - podmonitors
          - probes
          - servicemonitors
        verbs: [get, list, watch]
      - apiGroups: [monitoring.coreos.com]
        resources:
          - podmonitors/finalizers
          - probes/finalizers
          - servicemonitors/finalizers
        verbs: [get, list, watch, update]
      - apiGroups: [""]
        resources:
          - namespaces
          - nodes
        verbs: [get, list, watch]
      - apiGroups: [""]
        resources:
          - secrets
          - services
          - configmaps
          - endpoints
        verbs: [get, list, watch, create, update, patch, delete]
      - apiGroups: ["apps"]
        resources:
          - statefulsets
          - daemonsets
          - deployments
        verbs: [get, list, watch, create, update, patch, delete]
# -- The service account the pods will use to interact with the Kubernetes API
serviceAccount:
  main:
    enabled: true
    primary: true

# -- If both are set, Agent Operator will create and maintain a service for scraping kubelets
# https://grafana.com/docs/agent/latest/operator/getting-started/#monitor-kubelets
kubeletService:
  namespace: default
  serviceName: kubelet
