image:
  pullPolicy: IfNotPresent
  repository: tccr.io/tccr/alpine
  tag: latest@sha256:6dc807ae4f2867cb2d00d061f8f579f1966420ad792c179ac68072ab235109f8
manifestManager:
  enabled: false
operator:
  register: true
portal:
  open:
    enabled: false
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
workload:
  main:
    enabled: false

velero:
  configuration:
    backupStorageLocation: []
    volumeSnapshotLocation: []
  deployNodeAgent: true
  initContainers:
    - image: openebs/velero-plugin:3.6.0@sha256:9ea3331d891e436a7239e37e68ca4c8888500cb122be7cdc9d8400f345555c76
      imagePullPolicy: IfNotPresent
      name: openebs-velero-plugin
      volumeMounts:
        - mountPath: /target
          name: plugins
    - image: velero/velero-plugin-for-csi:v0.7.0@sha256:3ba643989cd2128963cfd5914de28acaa061e8216999e44330fd64a647c503ff
      imagePullPolicy: IfNotPresent
      name: velero-plugin-for-csi
      volumeMounts:
        - mountPath: /target
          name: plugins
    - image: velero/velero-plugin-for-aws:v1.9.0@sha256:198955f28c21fbf8d5e3a343a7660684f12bdd62d6f27c74ed3ca6cf31c87cec
      imagePullPolicy: IfNotPresent
      name: velero-plugin-for-aws
      volumeMounts:
        - mountPath: /target
          name: plugins
  nodeAgent:
    podVolumePath: /var/lib/kubelet/pods
    privileged: true
    resources:
      limits:
        cpu: 2000m
        memory: 2048Mi
  resources:
    limits:
      cpu: 4000m
      memory: 4Gi
  schedules: {}
schedules:
  default:
    templates:
      includedNamespaces:
        - ix-*
