image:
  repository: tccr.io/tccr/alpine
  pullPolicy: IfNotPresent
  tag: latest@sha256:e39cbd520ba256f371e306d8abc43d2f5fcd11bde060967fd2cd2233221e577b

service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

workload:
  main:
    enabled: false

portal:
  open:
    enabled: false

operator:
  register: true

manifestManager:
  enabled: false
