name: CI

on: [push]

jobs:
  build-deb:
    runs-on: ubuntu-latest
    container:
      image: tccr.io/truecharts/catalog_validation:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build deb package
        run: >
          dpkg-buildpackage
          -B
          --no-sign
          -jauto

      - name: Create artifacts dir
        run: mkdir artifacts
        if: success()

      - name: Move artifacts
        run: mv ../*.deb artifacts
        if: success()

      - uses: actions/upload-artifact@v4
        with:
          name: py-catalog-validation
          path: artifacts
        if: success()
